//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LernsituationOOP.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LernsituationOOP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Login ist nicht vorhanden oder die Angeben sind inkorrekt! 
        ///
        ///Bitte legen Sie einen neuen Mitarbeiter an! ähnelt.
        /// </summary>
        internal static string MsgBoxNoLogin {
            get {
                return ResourceManager.GetString("MsgBoxNoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mitarbeiter nicht gefunden! ähnelt.
        /// </summary>
        internal static string MsgBoxNoLoginTitle {
            get {
                return ResourceManager.GetString("MsgBoxNoLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es sind keine Reservierungen vorhanden! ähnelt.
        /// </summary>
        internal static string MsgBoxNoRes {
            get {
                return ResourceManager.GetString("MsgBoxNoRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fahrzeug Reserviert! ähnelt.
        /// </summary>
        internal static string MsgBoxRes {
            get {
                return ResourceManager.GetString("MsgBoxRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reservierung bearbeitet! ähnelt.
        /// </summary>
        internal static string MsgBoxResPrüfen {
            get {
                return ResourceManager.GetString("MsgBoxResPrüfen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abgeschlossen! ähnelt.
        /// </summary>
        internal static string MsgBoxTitle_ABGESCHLOSSEN {
            get {
                return ResourceManager.GetString("MsgBoxTitle_ABGESCHLOSSEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Achtung! ähnelt.
        /// </summary>
        internal static string MsgBoxTitle_ACHTUNG {
            get {
                return ResourceManager.GetString("MsgBoxTitle_ACHTUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler! ähnelt.
        /// </summary>
        internal static string MsgBoxTitle_FEHLER {
            get {
                return ResourceManager.GetString("MsgBoxTitle_FEHLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte gebe einen gültige Adresse an! ähnelt.
        /// </summary>
        internal static string validateAdress {
            get {
                return ResourceManager.GetString("validateAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du musst mindestens 18 Jahre alt sein! ähnelt.
        /// </summary>
        internal static string validateAge {
            get {
                return ResourceManager.GetString("validateAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte gebe einen gültige E-Mail an! ähnelt.
        /// </summary>
        internal static string validateEmail {
            get {
                return ResourceManager.GetString("validateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte gebe einen sinvollen Vornamen an! ähnelt.
        /// </summary>
        internal static string validateFirstName {
            get {
                return ResourceManager.GetString("validateFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte gebe einen sinvollen Nachnamen an! ähnelt.
        /// </summary>
        internal static string validateLastName {
            get {
                return ResourceManager.GetString("validateLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte gebe einen gültige Telefonnummer an! ähnelt.
        /// </summary>
        internal static string validatePhoneNumber {
            get {
                return ResourceManager.GetString("validatePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte gebe einen Passwort mit mindestens 8 Zeichen an! ähnelt.
        /// </summary>
        internal static string validatePW {
            get {
                return ResourceManager.GetString("validatePW", resourceCulture);
            }
        }
    }
}
