name: CI

on: [push, pull_request]

jobs:
  check-quality:
    runs-on: ubuntu-latest
    name: A job to check my code quality
    steps:
    - name: Check code meets quality standards
      id: code-inspector
      uses: codeinspectorio/github-action@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        code_inspector_access_key: ${{ secrets.CODE_INSPECTOR_ACCESS_KEY }}
        code_inspector_secret_key: ${{ secrets.CODE_INSPECTOR_SECRET_KEY }}
        min_quality_grade: 'EXCELLENT'
        min_quality_score: '100'
        max_defects_rate: '0.0001'
        max_complex_functions_rate: '0.4'
        max_long_functions_rate: '0.4'
        project_name: 'LERNSITUATIONOOP'
        max_timeout_sec: '600'

  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '1 month'
        # Optional inputs
        # skip-tags: true
        # skip-recent: 5

  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      
    - name: Restore NuGet Packages
      run: nuget restore LernsituationOOP/LernsituationOOP.sln
      
    - name: Build 
      run: msbuild LernsituationOOP/LernsituationOOP.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: LernsituationOOP
        path: LernsituationOOP\bin\Release\
